#unarchive module using variables
---
- name: using archive and unarchive 
  hosts: all
  become: yes

  tasks:

   - name: archive module; creating a zip file
     archive:
      path: /usr/src/security/*
      dest: /opt/security/games.tar.gz
      owner: '1001'
      group: '1001'
      mode: 0655

   - name: unarchive module; extracting a zip file
     unarchive:
      src: /usr/src/security/devops.zip # "extract:yes" is already covered by src
      dest: /opt/security/
      owner: "{{ansible_user}}"
      group: '1001'
      mode: 0644