#create files on multiple servers
---
- hosts: all
  become: yes
  tasks:
    - name: files on servers
      ansible.builtin.file:
        path: /opt/app.txt
        state: touch
        mode: '0655'
        owner: '1001'
        group: '1001'