   #insert line in a file by regexp or relative to other lines
---
- name: insert line in a file
  hosts: all
  become: yes

  tasks:
   - name: edit httpd.conf
     lineinfile:
      path: /etc/httpd/conf/httpd.conf
      regexp: "^DocumentRoot"
      line: "DocumentRoot \"/var/www/html/myroot\""
      #insertafter: 'BOF'     ///insertafter or insertbefore when needed
      backup: yes