 ---
- name: using template
  hosts: all
  become: yes
  
  tasks:
 - name: copy php info template to document root
     template:
      src: ~/playbooks/templates/phpinfo.php.j2
      dest: /var/www/html/myroot/phpinfo.php
      owner: apache
      group: apache  
      mode: 0644