prerequisites:
  - ca-certificates
  - curl

docker_packages:
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - docker-compose-plugin
  - docker-buildx-plugin

docker_services:
  - docker
  - containerd